// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	douyin_comment "minitok/cmd/api/biz/router/douyin/comment"
	douyin_favorite "minitok/cmd/api/biz/router/douyin/favorite"
	douyin_feed "minitok/cmd/api/biz/router/douyin/feed"
	douyin_message "minitok/cmd/api/biz/router/douyin/message"
	douyin_publish "minitok/cmd/api/biz/router/douyin/publish"
	douyin_relation "minitok/cmd/api/biz/router/douyin/relation"
	douyin_user "minitok/cmd/api/biz/router/douyin/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	douyin_relation.Register(r)

	douyin_comment.Register(r)

	douyin_message.Register(r)

	douyin_favorite.Register(r)

	douyin_feed.Register(r)

	douyin_publish.Register(r)

	douyin_user.Register(r)
}
