mysql:  
  host: 192.168.0.101
  port: 3306
  database: TikTokLite
  username: user
  password: 123
minio:
  #minio服务主机ip，需要填具体ip
  host: 192.168.0.101
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  videobuckets: video
  picbuckets: pic
redis:
  address: 192.168.0.101
  network: tcp
  port: 6379
  auth: 123
videofile_path: /tmp/file/video/
logfile_path: /tmp/file/log/
picfile_path: /tmp/file/picture/
level: info
