# MySQL数据库连接配置
mysql:
  host: ""
  port: ""
  db-name: ""
  username: ""
  password: ""
  config: charset=utf8mb4&parseTime=True&loc=Local

# JWT配置
jwt:
  signing-key: ""
  expires-time: ""
  issuer: ""
  subject: ""

# Etcd服务注册
etcd:
  host: ""
  port: ""

# RPC服务
rpc_server:
  service-name: ""
  host: ""
  port: ""

# 静态资源
static_resource:
  default-avatar: ""
  default-background-image: ""

# Redis数据库连接配置
redis:
  host: ""
  port: ""
  db: ""
  password: ""

# 文件上传和访问
file_access:
  upload_path: "" # 文件上传路径
  nginx_url: "" # nginx服务地址 http://127.0.0.1:8081/

# Redis缓存过期时间
cache_expire:
  null-key: "" # 空值缓存
  user-base-info: ""
  video-info: ""

# MongoDB数据库连接配置
mongodb:
  host: ""
  port: ""
  username: ""
  password: ""
  database: ""
